spring.datasource.url=jdbc:postgresql://bigear-mink-11746.jxf.gcp-europe-west3.cockroachlabs.cloud:26257/_migration_internal_dvorane_sql_1_1768294719?sslmode=verify-full&sslrootcert=C:/Users/Magdalena/AppData/Roaming/postgresql/root.crt
spring.datasource.username=magdalena
spring.datasource.password=7jO7Iy_cCZIVF1B4puKKUg
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080