# Supabase povezava
spring.datasource.url=jdbc:postgresql://db.jlqfvztulmnppahxdouj.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=p64hZ0C93gg8msw6
spring.datasource.driver-class-name=org.postgresql.Driver

#
spring.datasource.hikari.connection-timeout=30000

server.port=8080